### ISSUE TITLE
Use impl trait in library macro

### ISSUE THREAD

**Issue by JayPavlina** [8BitMate/reflect#5]
I am trying to do this:

```
reflect::library! {
    extern crate hashing {
        type Hasher;

        trait Hashable {
            fn hash(&self, &mut impl Hasher);
        }

        macro write;
    }
}
```

However, it will not accept the impl keyword. Is there any way to make it work, or do I have to use a type parameter instead?

**Comment by 8BitMate** [comment]
This is unfortunately not supported yet. It should work with the `dyn` keyword, or with a type parameter as you suggested.
